eggjs/egg-scripts

lib/cmd/start.js
test/start.test.js

https://github.com/eggjs/egg/issues/1353

fix: should set title correct

---

README.md

docs: fix stop typo

---

lib/cmd/start.js
test/fixtures/example/node_modules/custom-framework/index.js
test/start.test.js

fix: should not pass undefined env

---

test/fixtures/cluster-config/app/router.js
test/fixtures/cluster-config/config/config.default.js
test/fixtures/cluster-config/config/config.prod.js
test/fixtures/cluster-config/package.json
test/start.test.js

https://github.com/eggjs/egg/issues/1353#issuecomment-325725055

test: add cluster-config fixture

---

lib/cmd/start.js
lib/cmd/stop.js
test/start.test.js
test/stop.test.js

feat: log success at daemon mode

---

lib/cmd/start.js
package.json
test/fixtures/example/app/router.js
test/start.test.js
test/stop.test.js

- export this.child
- support customize stdout and stderr

refactor: modify the directory of logDir

---

README.md
lib/cmd/start.js
package.json

feat: add eggctl bin

---

lib/cmd/start.js
test/fixtures/subdir-as-basedir/base-dir/app/router.js
test/fixtures/subdir-as-basedir/base-dir/config/config.default.js
test/fixtures/subdir-as-basedir/base-dir/package.json
test/fixtures/subdir-as-basedir/package.json
test/start.test.js

feat: cwd maybe not baseDir

---

README.md
lib/cmd/start.js
lib/cmd/stop.js
package.json
test/stop.test.js

- close https://github.com/eggjs/egg/issues/1735
- close https://github.com/eggjs/egg/issues/1733
- relate: https://github.com/eggjs/egg-scripts/pull/12#issuecomment-344158657
- remove `stop baseDir` support
- ~~change egg to 2~~

feat: support stop --title

---

test/stop.test.js

test: add testcase for #12

---

README.md
lib/cmd/start.js

chore: add description for ignore-stderr

---

lib/cmd/start.js
package.json
test/start.test.js

refactor: raw spawn call to instead of helper.spawn in start non-daemon mode

---

LICENSE
README.md
package.json

chore: add license and issues link

---

lib/cmd/start.js
package.json
test/fixtures/ipc-bin/start.js
test/start.test.js

feat: add ipc channel in nonDaemon mode

---

lib/helper.js

stop command
Closes [#2896](https://github.com/eggjs/egg/issues/2896)

refactor: replace command by args in ps

---

README.md
lib/cmd/start.js
test/egg-scripts.test.js
test/start.test.js

 feat: support customize node path

---

lib/cmd/stop.js

当无 master pids 的时候，可以不用进行sleep 操作

feat(stop): only sleep when master process exists

---

.gitignore
README.md
lib/cmd/start.js
lib/command.js
test/fixtures/egg-scripts-config/app.js
test/fixtures/egg-scripts-config/config/config.default.js
test/fixtures/egg-scripts-config/node_modules/custom-framework/index.js
test/fixtures/egg-scripts-config/node_modules/custom-framework/package.json
test/fixtures/egg-scripts-config/package.json
test/start.test.js

feat: support eggScriptsConfig in package.json

---

README.md
lib/cmd/stop.js
test/fixtures/stop-timeout/app.js
test/fixtures/stop-timeout/app/router.js
test/fixtures/stop-timeout/config/config.default.js
test/fixtures/stop-timeout/package.json
test/stop.test.js

feat: support stop timeout

---

.github/workflows/nodejs.yml
lib/cmd/start.js
package.json
test/fixtures/example/app.js
test/fixtures/ipc-bin/start.js
test/start.test.js
test/ts.test.js

add `--no-deprecation` as default execArgv to avoid some log like `DeprecationWarning: Buffer() is deprecated` to stderr which will break startup unnecessary.

feat: --no-deprecation

---

.github/workflows/nodejs.yml
lib/command.js
test/fixtures/pkg-config/config/config.default.js
test/fixtures/pkg-config/inject.js
test/fixtures/pkg-config/package.json
test/start.test.js

Revert "feat: support pkgInfo.egg.require"

---

test/fixtures/pkg-config/inject.js
test/fixtures/pkg-config/inject1.js
test/fixtures/pkg-config/inject2.js
test/fixtures/pkg-config/node_modules/inject/index.js
test/fixtures/pkg-config/package.json
test/start.test.js

none.
* add the test case for injecting incorrect script.

test: case for injecting incorrect script

---

lib/command.js
test/fixtures/pkg-config-sourcemap/config/config.default.js
test/fixtures/pkg-config-sourcemap/config/plugin.js
test/fixtures/pkg-config-sourcemap/node_modules/custom-framework/index.js
test/fixtures/pkg-config-sourcemap/node_modules/custom-framework/package.json
test/fixtures/pkg-config-sourcemap/node_modules/inject/index.js
test/fixtures/pkg-config-sourcemap/package.json
test/start.test.js

fix: sourcemap default value should respect eggScriptConfig

---

README.md

docs(doc): 修改readme文档中的stop脚本处的描述，并增加示例.

---

.github/workflows/nodejs.yml
lib/cmd/start.js
test/fixtures/example/app.js
test/fixtures/trace-warnings/app.js
test/fixtures/trace-warnings/package.json
test/start.test.js
test/stop.test.js

start  ensure no stderr, so open --trace-warnings will helpful for debug

feat: --trace-warnings

---

README.md
lib/command.js
test/fixtures/egg-scripts-node-options/app.js
test/fixtures/egg-scripts-node-options/config/config.default.js
test/fixtures/egg-scripts-node-options/package.json
test/start.test.js

https://github.com/eggjs/egg-scripts/pull/41/files#r860521489

feat: eggScriptsConfig support node-options
